# Generated by Django 3.2.9 on 2021-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girls',
            name='color',
            field=models.CharField(choices=[('1', 'Choco'), ('2', 'Blondinka'), ('3', 'Rijinkiy'), ('4', 'Jaydari')], default='1', max_length=15),
        ),
    ]
